### ISSUE TITLE
Project should inherit from /dkpro-parent-pom

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-argumentation#1]
The project should inherit from the DKPro parent pom (which in turn inherits from the Sonatype OSS parent pom and contains everything necessary for deployment on Maven Central).

https://github.com/dkpro/dkpro-parent-pom/releases/tag/dkpro-parent-pom-10

**Comment by habernal** [comment]
According to: http://central.sonatype.org/pages/apache-maven.html

> Deprecated oss-parent
> In the past all the plugin configuration and other setup was managed by a Maven parent POM with the latest coordinates of org.sonatype.oss:oss-parent:9. This project leaked SCM, URL and other details and its usage is discouraged. Maintenance of the project has stopped and it no longer works with latest tooling such as Maven versions or Java versions. If desired, please manage your own organization-level POM in a similar manner.

**Comment by reckart** [comment]
I didn't know it was deprecated. Anyway, it still works and the dkpro-parent-pom 10 also works for Java 7 (version 12 is for Java 8). But if the Sonatype OSS pom is deprecated, then we should move the settings related to Maven Central into the dkpro-parent-pom. I have opened a respective issue:

https://github.com/dkpro/dkpro-parent-pom/issues/5

The dkpro-parent-pom also does additional things such as making sure that NOTICE.txt and LICENSE.txt files end up in the JARs, providing profiles for license checking and tuning Maven quality checking plugins for recent Java versions.

**Comment by habernal** [comment]
Alright; will change to dkpro-parent-pom once dkpro/dkpro-parent-pom#5 is resolved.

**Comment by reckart** [comment]
I don't think you have to wait for that. We've been releasing stuff to Maven Central based on dkpro-parent-pom:10 (Java 7) and 12 (Java 8) all the time and never hit a problem. I'm going to release a version 13 with dkpro/dkpro-parent-pom#5 fixed at some point, but I don't think it's a blocker for using the dkpro-parent-pom.

**Comment by reckart** [comment]
Please let me know if I'm missing something that makes dkpro/dkpro-parent-pom#5 a blocker because in that case I'd make it a priority to resolve it.

**Comment by habernal** [comment]
It's not a stopper. dkpro-parent-pom:10 (Java 7) should be fine. I'll look at that.
