### ISSUE TITLE
Module naming

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-argumentation#2]
The project uses the rather longish OSGi-inspired naming that we have used a lot in the past. Several projects are switching to the more Maven-default "dkpro-project-module" scheme, e.g. "dkpro-lab-core". It  also make the project better readable on Github.

Also, the groupId can be changed to "org.dkpro.project", e.g. "org.dkpro.lab" if desired.

**Comment by habernal** [comment]
Depends on #4

**Comment by reckart** [comment]
I don't think that renaming the modules and artifactId/groupId ni the argumentation project is in any way depending on DKPro Core 1.8.0 (#4). The artifactIds/etc. in DKPro Core will not change for the 1.8.0 release for compatibility reasons. This will only be done for a future 2.0.0 release.

**Comment by reckart** [comment]
The module folders should be renamed to match the artifactIDs.

**Comment by habernal** [comment]
What about the package names then? Should all be renamed, e.g., `de.tudarmstadt.ukp.dkpro.argumentation.preprocessing.annotation.ArgumentTokenBIOAnnotator` -> `org.dkpro.argumentation.preprocessing.annotation.ArgumentTokenBIOAnnotator` ?

**Comment by reckart** [comment]
Oh, I didn't notice that these have not been updated yet. The package names should have updated also along with changing the groupId. The groupId should always be a prefix of the packages names.

**Comment by reckart** [comment]
Mind that if you have custom UIMA types, the XML descriptors also need to be updated for the new package names.

**Comment by habernal** [comment]
Fixed
