### ISSUE TITLE
Upgrade to DKPro-Core 1.8.0

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-argumentation#4]
Once DKPro-Core 1..0 is released on Maven Central, the dependency should be updated (Java 8; Brat IO, renaming packages)

**Comment by reckart** [comment]
Only the dependency version needs to be updated. Packages/artifacts will not be renamed in DKPro Core 1.8.0.

**Comment by habernal** [comment]
Still not available, (ref https://github.com/dkpro/dkpro-core/issues/702 )
