### ISSUE TITLE
ArgumentBIOAnnotatorTest throwing exception

### ISSUE THREAD

**Issue by errantlinguist** [dkpro/dkpro-argumentation#6]
The test method `de.tudarmstadt.ukp.dkpro.argumentation.preprocessing.annotation.ArgumentBIOAnnotatorTest.testSimplifiedTokenBIO()` is throwing an `AnalysisEngineProcessException` but is not failing -- see the [Maven standard error output](https://github.com/dkpro/dkpro-argumentation/files/299855/mvn.err.txt).

**Comment by habernal** [comment]
AFAIK there is no way how to easily disable output when testing exceptions using `@Test(expected=...)` or `@Rule public ExpectedException exception = ExpectedException.none();`. See also http://stackoverflow.com/questions/9375704/ignoring-stacktrace-when-testing-for-exceptions-in-junit
The behavior of not-failing test is desired, testing functionality.

**Comment by reckart** [comment]
It would be possible to capture/redirect stdout/stderr... but usually we don't do that.

Cf. e.g. org.apache.uima.fit.testing.util.HideOutput.HideOutput()

**Comment by habernal** [comment]
Used HideOutput. Not nice, but did the job :)

**Comment by reckart** [comment]
Output should probably be restored in a finally block, otherwise it may actually not be restored due to the exception being thrown ;)

**Comment by habernal** [comment]
That's why I liked the first comment on the linked StackOv.: "There isn't a nice way to do this, and it's not worth it anyway." :)
